version: 2
jobs:
  build:
    branches:
      # ignore:
      #   - develop
      #   - /feature-.*/
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install
  lint:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build