version: 2
jobs:
  build:
    ignore:
      - develop
      - /feature-.*/
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install && yarn lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test